server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 192.168.230.128
    port: 6379
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  thymeleaf:
    cache: false
  rabbitmq: #\u914D\u7F6Erabbitmq\u7684\u57FA\u7840\u4FE1\u606F
    host: 192.168.230.128
    port: 5672
    virtual-host: /hehao
    username: hexhao
    password: hexhao
    publisher-confirm-type: correlated #设置异步确认
    publisher-returns: true #确认消息是否到达队列
    listener:
      simple:
        prefetch: 1
        concurrency: 8
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.atguigu.gmall: debug #\u8F93\u51FAsql\u8BED\u53E5
