server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true
#jwt:
#  pubKeyPath: E:\rsa\rsa.pub #\u516C\u94A5\u8DEF\u5F84
#  priKeyPath: E:\rsa\rsa.pri #\u79C1\u94A5\u8DEF\u5F84
#  secret: 123abc!@# #\u751F\u6210\u79C1\u94A5\u516C\u94A5\u9700\u8981\u7684\u76D0
#  expire: 180 #token\u8FC7\u671F\u65F6\u95F4
#  cookieName: GMALL-TOKEN #token\u540D\u79F0
#  unick: unick #\u767B\u5F55\u6210\u529F\u540E\u9875\u9762\u663E\u793A\u7684\u7528\u6237\u4FE1\u606F
